gameserver:
  port: 8345
  boss-count: 1
  worker-count: 10
  keep-alive: true
  backlog: 100
  webservice-url: http:\\localhost:8080\

---
spring:
  profiles: container

gameserver:
  port: ${PORT}
  boss-count: ${BOSS_COUNT}
  worker-count: ${WORKER_COUNT}
  keep-alive: ${KEEP_ALIVE}
  backlog: ${BACKLOG}
  webservice-url: ${WEBSERVICE_URL}