spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

gameserver:
  port: 666
  boss-count: 1
  worker-count: 10
  keep-alive: true
  backlog: 100
  webservice-url: http:\\localhost:8080\

---

spring:
  profiles: container

gameserver:
  port: ${PORT:666}
  boss-count: ${BOSS_COUNT:1}
  worker-count: ${WORKER_COUNT:10}
  keep-alive: ${KEEP_ALIVE:true}
  backlog: ${BACKLOG:100}
  webservice-url: ${WEBSERVICE_URL}